{% set name = "clFFT" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/clMathLibraries/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e7348c146ad48c6a3e6997b7702202ad3ee3b5df99edf7ef00bbacc21e897b12
  patches:
    # Fix a type issue when using sqrt
    # xref: https://github.com/clMathLibraries/clFFT/pull/199
    - PR_199.diff
    # Fix building with C++11
    # xref: https://github.com/clMathLibraries/clFFT/pull/184
    - PR_184.patch

build:
  number: 2

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - ocl-icd                    # [linux]
    - khronos-opencl-icd-loader  # [win or osx]

test:
  commands:
    # Check files
    - test -f "${PREFIX}/include/clFFT.h"           # [unix]
    - test -f "${PREFIX}/lib/libclFFT.so"           # [linux]
    - test -f "${PREFIX}/lib/libclFFT.dylib"        # [osx]
    - if not exist %LIBRARY_INC%\\clFFT.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\clFFT.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\clFFT.lib exit 1  # [win]

about:
  home: https://github.com/clMathLibraries/clFFT
  license: Apache-2.0
  license_file: LICENSE
  summary: A software library containing FFT functions written in OpenCL

extra:
  recipe-maintainers:
    - jakirkham
    - isuruf
