travis:
  secure:
    BINSTAR_TOKEN: gbnoLfBLll9oEOujUCb/p6deRGTRY2n/lj59QHAs3Sm3gK8qxX7Gxd3meSM2hlXCJmF56hhEpA8DPrWptTVF/V9w2PBVumw3xGEa0cggVanbUvgwVHldeLLUcxXSqPm4vxBEAaZigzapRtSixJYcvyZuL2Bepx5G73Fqtm4mGSlouX6hJnOH7luR/zUWdqlbTtaN5lU3p9JI69uGKQ3yIMCH/En7dGkQPadMKzbcrTS3HTWxjr4GcZPXLs5r7ktCZlBEVk08i7DDDONXiKTpo9o4TJqYBb8w4U73AfjZg16EfwAWg8xdY8gU3MuU7pPG65bjcrYwwLt9j7WSPBlHP3s8dx1c1WPtT84ccZZuLE1+6XzWIM/S8s4WcwUegbebzOR5lf8nemepDMbfON+fyIKbMoipjc7JARkFVUC6yOavbfapmS4ZOHNwtRQSn36PBqT8DnsR7hgZEOkIuVJulGKX/kxdIFbG4DluUk4OLaMIc4vkKxt23a31S5IpRuhdD5vkRo40ABWXquuSTkQwTtNBwE5Wt94Vp7ClF7t6ix6Gp+Rf8kL0g/TVGcc+aqCCtfsvTb+0ey5LvzXm8WqHo8gvUYS9+t9RHZa1anw97CJPAl6OAphCb94lmrApYNlkTFYhowe4GSsQJThXWe6NyyCPoIkE3hHz8m/hd8tDdE0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
