travis:
  secure:
    BINSTAR_TOKEN: C9sJeCC9tJul/1LT4x8R1qQY3VIpDdHh5CW5MlJnY7UPGT5f5qzwmxdRPnFHLXcFhmqZGwdc19O7aJbQ5s9zZRe3wH0ZuVntnclcQx7YcCda8/m/Nv+Ju5rsdAvpZsjdZ5RSaPRhHlINA1T9nxN0lE62uV9mWReJWuTuv0DCHPqTAWljoTswGimnI8EctTaz8pLkhzL0KeNjEvJHvNP5wwU2pwp5dTBsYpQa1PlB0uBqoHaQyKaLSSz9eOHClhihMVTipIyM/4iFZWuVVjHUXiu0LE09IvzzRyxtInePQX9uLj+bNuc/BPJGNgeSktSkmuj5Bzp04YJCpKjlDQiw5Nvokd89oskmUtD67JrgXi7Gwb0Yo4j1t1u5fV+j24t9ImvglN4ZWqgE3V7pKdfQUEo9IKgmXP1Pr3tbvJxQojSVL4C2z1Wzj5fQtCbChVAyQ1yh2F87sqZJvp1AhXI595Kl36u/WSMn+yp1qgICVUAdpKA1ZElyKQ+bmcXuNCKFdU2cXR66r8JPVf2MkJ9a7da8f82kyz811EXyvVA7cYnmywDOXL7cBQDrTxprh+CVnMABiuQ/NnFqNeCGuJYNFVy4zZ1gLu3A0SvrY4wNYs8blz7fJK6m6cEQ+r/k7SOY2fsmb79esOqS1MjH1lSsYXl5WRqOE3wQdpmQ92e85Ks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
